services:
  db:
    image: mysql:8.0
    container_name: autonova_sa
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autonova
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: openjdk:17-jdk-slim
    container_name: autonova
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./build:/app
    ports:
      - "8080:8080"
    command: ["java", "-jar", "autonova-0.0.1-SNAPSHOT.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/autonova_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data:
